version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

executors:
  aws-executor:
    docker:
      - image: cimg/python:3.6
    working_directory: ~/tmp
  java-mysql-executor:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/mysql:8.0.20
        environment:
          MYSQL_DATABASE: test_db
          MYSQL_USER: mysql_user
          MYSQL_PASSWORD: mysql_password
    working_directory: ~/tmp
  deploy-executor:
    docker:
      - image: cimg/base:stable

jobs:
  get_test_config:
    executor: aws-executor
    steps:
      - run: mkdir -p workspace
      - aws-s3/copy:
          from: s3://sustral-secrets/clientapi/test/application.properties
          to: ~/tmp/workspace/application.properties
      - persist_to_workspace:
          root: ~/tmp/workspace
          paths:
            - application.properties
  build:
    executor: java-mysql-executor
    steps:
      - checkout

      - attach_workspace:
          at: ~/tmp/workspace

      - run:
          name: Copy application.properties to test resources folder
          command: |
            cat ~/tmp/workspace/application.properties > ~/tmp/src/test/resources/application.properties

      - run:
          name: Wait for MySQL
          command: |
            for i in `seq 1 15`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed wait for MySQL && exit 1

      - run:
          name: Install MySQL CLI
          command: |
            sudo apt install default-mysql-client

      - run:
          name: Create DB schema
          command: |
            mysql -h 127.0.0.1 -u mysql_user -p mysql_password mysql> test_db < ~/tmp/src/main/resources/schema.sql

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonarqube -x test
  deploy:
    executor: deploy-executor
    steps:
      - run: echo "deploy"

workflows:
  main:
    jobs:
      - get_test_config:
          context: AWS_S3_sustral-secrets
      - build:
          context: SonarCloud
          requires:
            - get_test_config
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
