version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

executors:
  aws-executor:
    docker:
      - image: cimg/python:3.6
    working_directory: /wrk_dir
  java-mysql-executor:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/mysql:8.0.20
        environment:
          MYSQL_DATABASE: test_db
          MYSQL_USER: mysql_user
          MYSQL_PASSWORD: mysql_password
    working_directory: /wrk_dir
  deploy-executor:
    docker:
      - image: cimg/base:stable

jobs:
  get_test_config:
    executor: aws-executor
    steps:
      - run: mkdir -p workspace
      - aws-s3/copy:
          from: s3://sustral-secrets/clientapi/test/application.properties
          to: /wrk_dir/workspace/application.properties
      - persist_to_workspace:
          root: /wrk_dir/workspace
          paths:
            - application.properties
  build:
    executor: java-mysql-executor
    steps:
      - checkout

      - attach_workspace:
          at: /wrk_dir/workspace

      - run: cat /wrk_dir/workspace/application.properties >> /wrk_dir/src/test/resources/application.properties

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonarqube -x test
  deploy:
    executor: deploy-executor
    steps:
      - run: echo "deploy"

workflows:
  main:
    jobs:
      - get_test_config:
          context: AWS_S3_sustral-secrets
      - build:
          context: SonarCloud
          requires:
            - get_test_config
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
